name: Python application

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: 3.10
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        [ -f requirements.txt ] && pip install -r requirements.txt
    - name: Lint with flake8
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

  docker:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: aspdiscovery/images:app-${{ github.run_number }}

  modifygit:
    needs: docker
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        repository: 'aspdiscovery123/mainfest'
        token: ${{ secrets.GIT_PASSWORD }}
    - name: Modify the image
      run: |
        git config --global user.email "aspdiscovery@outlook.com"
        git config --global user.name "aspdiscovery123"
        sed -i "s+aspdiscovery123/images.*+aspdiscovery123/images:app-$RUN_NUMBER+g" deployment.yaml
        git add .
        git commit -m "Done by GitHub Actions Job changemanifest: ${{ github.run_number }}"
        git push origin main
      env:
        RUN_NUMBER: ${{ github.run_number }}
